language: d

d:
    - dmd
    - ldc
os:
    - linux

env:
    - UNRELIABLENETWORK=true

before_install:
    - sudo apt-get install -y libevent-dev

script:
    - dub test --config=std
    - dub test --config=vibed